### ISSUE TITLE
[feature request] turn() for all nodes (canvas item)

### ISSUE THREAD

**Issue by OlexiyKravchuk** [Kermer/Godot#1]
I think it was good if it was possible to turn() all (canvas item) of objects including nodes (control), I found a way how to do it without this function, but it's redundant, and does not always work as I would like to .

**Comment by Kermer** [comment]
It's strange that Control still doesn't use normal (like Node2D) transform, especially if you can just create a Node2D as its parent, adjust rotation, scale and it'll affect this Control.

You might create new issue on Godot github for adding transform to Control nodes.
Control nodes maybe lose some quality when rotating or scaling, but people will continue to do this, so transform would be better, more effective than another (parent) node.

**Comment by OlexiyKravchuk** [comment]
Oh, sorry, accidentally posted this question here, do not know how I got lost in the primary repository Godot, and could not find where my question in the list, and decided to is not to send, and then, re-posted, but the correct address. .. XD
